// One rated player-season. Generated by scripts/rate-players.py — the metric
// fields are non-null because unrateable rows (MP = 0) are dropped at generation.
export type RatedPlayerSeason = {
  Season: string;
  Rank: number;
  PlayerName: string;
  Age: number;
  TeamSlug: string[];
  Position: string;
  GamesPlayed: number;
  MinutesPlayed: number;
  PlayerEfficiencyRating: number;
  BoxPlusMinus: number;
  ValueOverReplacementPlayer: number;
  WinSharesPer48Min: number;
  PlayerSlug: string;
  Rating: number;
};
