// Generated by scripts/build-db-data.mts — do not edit by hand.
// Regenerate with `npm run build:db-data`.

import type { PlayoffParticipationRow } from "@/types/db-data";

export const PLAYOFF_PARTICIPATION: PlayoffParticipationRow[] = [
];
